#!/bin/bash
function pause(){
   read -p "$*"
}
red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 4`
reset=`tput sgr0`
#echo "${red}red text ${green}green text${reset}"
rm -f *_temp* # necesario verificar si hay archivos temp existentes. Así da un error, que no se llega a ver
#echo $(awk '$1~/lista_ju/ {print $2, $3, $4}' files/textos)
#more files/jugadores_productos.hist
#echo $(awk '$1~/jugador/ {print $2}' files/textos)
#### alternativa con ventanas
nombre_jugadorq=$(zenity --list --title="Escoge tu nombre" --column="Jugadores" $(cat files/jugadores_productos.hist) "Nuevo jugador")
if [ "$nombre_jugadorq" == "Nuevo jugador" ]
then
nombre_jugador=$(zenity --entry --entry-text="Type" --text="Escribe nombre del nuevo jugador")
else
nombre_jugador=$nombre_jugadorq
fi
#### fin de alternativa con ventanas
#read nombre_jugador
jugador_existe=$(grep -Fxq $nombre_jugador files/jugadores_productos.hist ; [ $? -eq 0 ] && echo 1 || echo 0)
if [ "$jugador_existe" == 1 ]
then
awk '$6~/'$nombre_jugador'/ {'nivel_ant='$7; print "Hola", $6 ". Jugaste por última vez el día", strftime("%c ", $3)". Hace", int(('$(date -u +%s)'-$3)/86400), "días y", (('$(date -u +%s)'-$3)%86400)/3600, "horas.\n\n" "Jugaste en el nivel", $7"\n\n"}' files/productos.hist|tail -n 5
nivel_ant=$(awk '$6~/'$nombre_jugador'/ {print $7}' files/productos.hist|tail -n 1)
echo "Tus tres mejores desempeños sin fallas para el nivel" $nivel_ant "fueron"$'\nOK\tX\tFecha'
awk '$6~/'$nombre_jugador'/ && $5~/0/ && $7~/'$nivel_ant'/ {print $4 "\t" $5 "\t" strftime("%c ", $3)}' files/productos.hist |sort -k1,2 -n -r|head -n 3
echo "Tus tres mejores desempeños incluyendo fallas para el nivel" $nivel_ant "fueron"$'\nOK\tX\tFecha'
awk '$6~/'$nombre_jugador'/ && $7~/'$nivel_ant'/ {print $4 "\t" $5 "\t" strftime("%c ", $3)}' files/productos.hist |sort -k1,2 -n -r|head -n 3
#echo "Selecciona el rango de tablas con el que quieres jugar. Primera tabla:"
#echo "(o selecciona e: entrenamiento adaptativo puntos débiles)"
#read seleccion
seleccion=$(zenity --list --title="Selecciona el rango de tablas con el que quieres jugar. Primera tabla:" --column="Tabla" 2 3 4 5 6 7 8 9 "Entrenamiento adaptativo")
if [ "$seleccion" == "Entrenamiento adaptativo" ]
then
	nivel=Adaptativo
else
	nivel1=$seleccion
	#echo "Segunda tabla"
	#read nivel2
	nivel2=$(zenity --list --title="Selecciona el rango de tablas con el que quieres jugar. Primera tabla:" --column="Tabla" 2 3 4 5 6 7 8 9)
	nivel=$nivel1-$nivel2
fi
else
	echo $nombre_jugador >> files/jugadores_productos.hist
	sort files/jugadores_productos.hist|uniq > jugadores_n
	mv jugadores_n files/jugadores_productos.hist 
	#echo "Selecciona el rango de tablas con el que quieres jugar. Primera tabla:"
	#read nivel1
	nivel1=$(zenity --list --title="Selecciona el rango de tablas con el que quieres jugar. Primera tabla:" --column="Tabla" 2 3 4 5 6 7 8 9)
	#echo "Segunda tabla"
	#read nivel2
	nivel2=$(zenity --list --title="Selecciona el rango de tablas con el que quieres jugar. Primera tabla:" --column="Tabla" 2 3 4 5 6 7 8 9)
	nivel=$nivel1-$nivel2
fi
if [ "$nivel" != 'Adaptativo' ]
then
	sed -e 's/sustituir_nivel1/'$nivel1'/' files/lista_productos.awk > lista_productos_temp.awk
	sed -i -e 's/sustituir_nivel2/'$nivel2'/' lista_productos_temp.awk
	lista_de_operaciones=($(awk -f lista_productos_temp.awk files/productos.hist))
else
	sed -e 's/quien_juega/'$nombre_jugador'/' files/adaptativo.awk > adaptativo_temp.awk
	lista_de_operaciones=($(awk -f adaptativo_temp.awk files/productos.hist))
fi
prod_num=0
jugar=y
sesion=$(awk 'BEGIN{sesion=0}$4~/'$nombre_jugador'/ && $2~/Sesion_final/ {sesion=$3}END{print sesion}' files/productos.hist)
let "sesion += 1"
echo "# Inicio_de_Sesion" $sesion $nombre_jugador >> historial_productos_temp
repeticion=0
	echo 2 0 > grafica_promedios_temp
	gnuplot < promedios.plot
	eog promedios_temp.png &
while [ "$jugar" != "n" ]; do
	#pause 'presiona ENTER para comenzar la sesión ...'
	zenity --info --text="presiona OK para comenzar la sesión ..."	
	tic=$(date -u +%s)
	echo "# Historial" $tic $nombre_jugador $(date -d @$tic) >> historial_productos_temp
	echo "# Check" $'\t' "S1" $'\t' "S2" $'\t' "User" $'\t' "Prog" $'\t' "Time" $'\t' "Jugad" $'\t' "Nivel" >> historial_productos_temp
	bien=0
	mal=0
	toc=1
	t_final=20
	while [ "$toc" -le "$t_final" ]; do
		fac1=$((${lista_de_operaciones[prod_num]}/100))
		fac2=$((${lista_de_operaciones[prod_num]}%100))
		clear
		echo $fac1" x "$fac2 $'\t \t' ${green}$bien${reset}" OK" $'\t' ${red}$mal${reset}" X"
		tiki=$(date -u +%s%N)
		read producto
		toki=$(date -u +%s%N)
		let "toc += 1"
		let "prod_num=($prod_num+1)%1000"
		if [ "$producto" = "$(($fac1*$fac2))" ]
		then
			let "bien+=1"
			echo "OK" $'\t' $fac1 $'\t' $fac2 $'\t' $producto $'\t' $(($fac1*$fac2)) $'\t' $((($toki-$tiki)/1000000)) $'\t' $nombre_jugador $'\t' $nivel >> historial_productos_temp
		else
			let "mal+=1"
			echo "X" $'\t' $fac1 $'\t' $fac2 $'\t' $producto $'\t' $(($fac1*$fac2)) $'\t' $((($toki-$tiki)/1000000)) $'\t' $nombre_jugador $'\t' $nivel >> historial_productos_temp
			echo /usr/games/fortune | cowsay "Incorrecto. Recuerda" $'\n\n\t' $fac1" x "$fac2" = "$(($fac1*$fac2))
			echo "Incorrecto. Recuerda" $'\n\n\t' $fac1" x "$fac2" = "$(($fac1*$fac2)) > vacadice_temp
			#pause 'presiona ENTER para continuar ...'
			zenity --text-info --filename=vacadice_temp
			let "t_final+=1"
		fi
	done
	let "repeticion+=1"
	echo "Serie número" $repeticion $'\n'"Tus resultados"$'\nAciertos\tFallos\n'${green}$bien${reset}$'\t\t'${red}$mal${reset}
	echo "# Resumen" $tic $'\t' $bien $'\t' $mal $'\t' $nombre_jugador $nivel >> historial_productos_temp
	#echo echo /usr/games/fortune | cowsay "¿Seguir jugando?" $'\n\t' "Presiona ENTER" $'\n' "¿Parar?"  $'\n\t' "Escribe n y presiona ENTER para terminar..."
	#read jugar
	awk -f files/promedios.awk historial_productos_temp|sort > grafica_promedios_temp
	gnuplot < promedios.plot
	zenity --timeout 120 --question --text="¿Quieres seguir jugando?"
	case $? in
	0) jugar=y
	;;
	1) jugar=n
	;;
	esac
	clear
done
echo "# Final_de_sesión" $sesion $nombre_jugador "Num_repeticiones" $repeticion >> historial_productos_temp
clear
echo "¡Chao" $nombre_jugador", regresa pronto!"
cat historial_productos_temp >> files/productos.hist
rm *_temp*
#Mejores números
echo "Historial" $nombre_jugador
echo "Tus tres mejores desempeños sin fallas para el nivel" $nivel "fueron"$'\nOK\tX\tFecha'
awk '$6~/'$nombre_jugador'/ && $5~/0/ && $7~/'$nivel'/ {print $4 "\t" $5 "\t" strftime("%c ", $3)}' files/productos.hist |sort -k1,2 -n -r|head -n 3
echo "Tus tres mejores desempeños incluyendo fallas para el nivel" $nivel "fueron"$'\nOK\tX\tFecha'
awk '$6~/'$nombre_jugador'/ && $7~/'$nivel'/ {print $4 "\t" $5 "\t" strftime("%c ", $3)}' files/productos.hist |sort -k1,2 -n -r|head -n 3
#pause 'presiona ENTER para terminar ...'
zenity --timeout 10 --info --text="presiona OK para terminar la sesión ..."
